### ISSUE TITLE
GUI does not appear

### ISSUE THREAD

**Issue by alecjacobson** [pressureless/linear_algebra#18]
I think I got the dependencies installed. Now if I issue:

    python linear_algebra.py

or

    python linear_algebra.py --GUI

I see this message and the program exits:

```
pdfviewer using PyMuPDF (GPL)
This program needs access to the screen. Please run with a
Framework build of python, and only when you are logged in
on the main display of your Mac.
```

Is this a bug? Or, perhaps I'm calling it incorrectly?

**Comment by alecjacobson** [comment]
I'm really striking out trying to install this...

Here's another thing I tried (still fails eventually, but looks like it gets a bit farther?):

```
conda create --name iheartla python=3.7
conda activate iheartla
conda install wxPython
pip install tatsu regex  PyMuPDF graphviz cppyy
pythonw linear_algebra.py --GUI
```

following [this advice](https://stackoverflow.com/questions/48531006/wxpython-this-program-needs-access-to-the-screen), but I see the context switch from my terminal briefly (like an app launched) then crashes with this error:

```
pdfviewer using PyMuPDF (GPL)
Traceback (most recent call last):
  File "linear_algebra.py", line 23, in <module>
    show_gui()
  File "linear_algebra.py", line 10, in show_gui
    MainWindow(None, "I❤️LA")
  File "/Users/ajx/Repos/iheartla/la_gui/frame.py", line 101, in __init__
    self.midPanel = MidPanel(self)
  File "/Users/ajx/Repos/iheartla/la_gui/mid_panel.py", line 16, in __init__
    self.cpp_ctrl = CppTextControl(self)
  File "/Users/ajx/Repos/iheartla/la_gui/cpp_ctrl.py", line 41, in __init__
    self.StyleSetBackground(wx.stc.STC_C_PREPROCESSORCOMMENTDOC, bc.BACKGROUND_COLOR)
AttributeError: module 'wx.stc' has no attribute 'STC_C_PREPROCESSORCOMMENTDOC'
```

I'm wondering if we should write the GUI in matlab ;-)

**Comment by pressureless** [comment]
Someone encountered this problem before. This suggestion worked for him: Create a virtual environment for pipenv manually with ```python3 -m venv .venv``` before you run ```pipenv install```.
It's a good idea to write the GUI in matlab, maybe we can try later.

**Comment by yig** [comment]
How did you install to get the error message at the top, "This program needs access to the screen. Please run with a Framework build of python, and only when you are logged in on the main display of your Mac."?

Was that also conda?

What do you get in your conda environment if you type: `python3 -c 'import wx; print(wx.__version__)'`?

**Comment by pressureless** [comment]
When we can't run the GUI, the command line version will also not behave as expected
![image](https://user-images.githubusercontent.com/8511053/117708062-5b9e1280-b19d-11eb-9864-ce63c6605308.png)

**Comment by alecjacobson** [comment]
Still haven't successfully managed to get the GUI to appear. I'm now using conda via https://github.com/pressureless/linear_algebra/issues/52#issuecomment-841223614
but if I try

    pythonw app.py
    
I get an error

```
Traceback (most recent call last):
  File "app.py", line 1, in <module>
    import iheartla.la_tools.la_helper as la_helper
  File "/Users/ajx/Repos/iheartla/iheartla/la_tools/la_helper.py", line 1, in <module>
    from enum import Enum, IntFlag
ImportError: cannot import name IntFlag
```

**Comment by yig** [comment]
As per https://stackoverflow.com/a/45716067/328840 , you might try: `pip uninstall enum` in case you at one point installed a package that now shadows a built-in module.

**Comment by alecjacobson** [comment]
WARNING: Skipping enum as it is not installed.

**Comment by yig** [comment]
Also `pip uninstall enum34`

**Comment by alecjacobson** [comment]
WARNING: Skipping enum34 as it is not installed.

>

**Comment by yig** [comment]
What do you get for ```python -V``` and ```pip -V```?

**Comment by alecjacobson** [comment]
Python 3.8.10

pip 21.1.1 from
/Users/ajx/opt/miniconda3/envs/iheartla/lib/python3.8/site-packages/pip
(python 3.8)

>

**Comment by yig** [comment]
And if you type `python` and then `from enum import IntFlag`?

**Comment by alecjacobson** [comment]
nothing happens (I'm assuming success)

>

**Comment by alecjacobson** [comment]
wait, I'm I supposed to be using python or pythonw for the gui? (neither
work but if I do python then I get an error

Traceback (most recent call last):

  File "app.py", line 42, in <module>

    show_gui()

  File "/Users/ajx/Repos/iheartla/iheartla/compiler.py", line 5, in show_gui

    from .la_gui.frame import wx, MainWindow

  File "/Users/ajx/Repos/iheartla/iheartla/la_gui/frame.py", line 2, in
<module>

    import wx

ModuleNotFoundError: No module named 'wx'

My pythonw -V outputs Python 2.7.16

>

**Comment by pressureless** [comment]
I❤️LA depends on Python 3.x
`wx` comes from the library `wxpython`

**Comment by yig** [comment]
Wait, your `pythonw -V` outputs Python 2.7.16? That's the problem. It's now using your conda python. Weird. For me:

```
yotam@yotronagon ~/W/G/i/code (master)> pythonw -V                                                                                             (iheartla) 
Python 3.8.10
yotam@yotronagon ~/W/G/i/code (master)> which pythonw                                                                                          (iheartla) 
/Users/yotam/opt/miniconda3/envs/iheartla/bin/pythonw
```

**Comment by alecjacobson** [comment]
I fixed it using https://github.com/pressureless/linear_algebra/pull/82 , not sure if this is an OK way to deal with conda names (they all had the same name before and conda complained).
