### ISSUE TITLE
Embed input in output

### ISSUE THREAD

**Issue by yig** [pressureless/linear_algebra#25]
The entire input I❤️LA code should be embedded as a comment near the top of the compiled output. That would make the output replicable and translatable into other languages.

**Comment by pressureless** [comment]
How about this way?
<img width="490" alt="image" src="https://user-images.githubusercontent.com/8511053/97949890-0bb04000-1d63-11eb-85e1-969a7b731d90.png">
<img width="369" alt="image" src="https://user-images.githubusercontent.com/8511053/97949900-11a62100-1d63-11eb-92d6-16ec2c798927.png">

**Comment by yig** [comment]
I like it.
