### ISSUE TITLE
ASCII aliases for non-ASCII characters

### ISSUE THREAD

**Issue by alyssarosenzweig** [pressureless/linear_algebra#26]
Depending on keyboard layout, entering non-ASCII mathematics characters might be cumbersome. From a cursory look at the grammar, it appears some aliases are available (for integration, for example) but some are not (for example for ℝ, it seems)?

Full LaTeX definitions like \mathbb{R} are needlessly cumbersome to type and would complicate parsing, but perhaps there are middle-grounds to make writing in the language more comfortable. (At the slight expense of readability, but if the goal is to _read_ formulae in the language without editing, it's probably better to render the LaTeX and read that instead.)

It may be worth looking at the approach taken by TLA+ which also has the plain-text/LaTeX dualism to contend with, although the use case is a bit different.

**Comment by yig** [comment]
Thank you for trying I❤️LA! I don't like to speak for everyone working on I❤️LA, but I will anyways based on what I think is our consensus point of view: Unicode characters should be first-class, and entering them isn't that difficult in most environments these days. We would like our GUI to make it easy, too.

On macOS, I have system-wide substitutions (System Preferences > Keyboard > Text) for the characters I use a lot, like \R for ℝ, \Z for ℤ, \times for ×, \in for ∈, \sum for ∑, \cdot for ⋅, ^T for ᵀ, etc. It was very easy for me to type those just now. Mine basically follow tex, but I simplified the mathbb.

Vim has digraphs: https://github.com/vim/vim/blob/master/runtime/doc/digraph.txt

I'd like to learn about emacs and Windows support for Unicode entry.

Our GUI editor's substitutions are a work in progress. We haven't spent a lot of time on them. The current list is here: https://github.com/pressureless/linear_algebra/blob/master/la_gui/la_ctrl.py#L25


{'R': 'ℝ', 'Z': 'ℤ', 'x': '×', 'times': '×', 'inf': '∞', 'in': '∈', 'sum': '∑',
                             'had': '○', 'kro': '⨂', 'dot': '⋅', 'T': 'ᵀ', 'par': '∂', 'emp': '∅',
                             'arr': '→', 'int': '∫', 'dbl': '‖', 'pi': 'π', 'sig': 'σ', 'rho': 'ρ',
                             'phi': 'ϕ', 'the': 'θ'}

In the latest release, you access them by typing \sum\ for ∑. In the latest unreleased version, I removed the trailing \ to follow tex.

**Comment by yig** [comment]
It looks like Emacs has a TeX input mode, among other ways to enter Unicode characters: https://www.emacswiki.org/emacs/UnicodeEncoding

**Comment by alyssarosenzweig** [comment]
Thanks, that explains the expected workflow. I may have missed the
documentation here, I didn't look too closely. Sorry for the noise.

**Comment by yig** [comment]
I genuinely appreciate your question and the opportunity to attempt an answer. It helps us work through what will work and won't work for our users. I hope you keep an eye on I❤️LA and try it at some point.
