### ISSUE TITLE
[feature request] scientific notation for numeric literals

### ISSUE THREAD

**Issue by alecjacobson** [pressureless/linear_algebra#38]
```I❤️LA
A = 4e8
```

current fails to compile. I'm not sure it should. This is ["E notation"](https://en.wikipedia.org/wiki/Scientific_notation#E_notation) and seems to be purely an artifact of ascii programming languages. 

On the chalkboard I think people would write something more like

```I❤️LA
A = 4×10⁸
```

Interestingly, this is a case where I think we really need a symbol for multiplication. It _would be fairly unclear_ to write

```I❤️LA 
A = 4 10⁸
```

Especially if we may eventually want to support writing long numbers with spaces:

```I❤️LA
A = 400 000 000
```

There was a new language that proposes using spaces like this (I can't remember which. Maybe @yig told me about it). Currently this compiles to `A = 400 * 0 * 0;`

**Comment by alecjacobson** [comment]
Ah! Currently we support scientific notation as:

```I❤️LA
A = 4⋅10⁸
```

Not sure if this was purely intention, but seems fine to me. (We still may want to consider this long numbers via spaces thing).

Meanwhile, I think we should support negative exponents:

```I❤️LA
A = 4⋅10⁻⁸
```

Currently this fails to compile:
```
(1:9) no available options :
A = 4⋅10⁻⁸
        ^
```

(We can of course do `A = 4⋅10^(-8)` in the meantime)

**Comment by pressureless** [comment]
We currently use the capital `E`. `A = 4E8` will work.  We put the lowercase `e` in `trigonometry` (`from trigonometry: e`) which only represents `M_E` in C++ or `np.e` in Python.

**Comment by pressureless** [comment]
The negative unicode symbol is not supported yet. Only `⁻¹` works now

**Comment by alecjacobson** [comment]
Thanks. I'll close this and separate into two new issues/requests.
