### ISSUE TITLE
Change to ebnf

### ISSUE THREAD

**Issue by alecjacobson** [pressureless/linear_algebra#52]
I'd like to try changing the `iheartla/la_grammar/operators_ebnf.py` file. However, my changes don't seem to make a difference. Even I delete the entire contents of this file, everything works the same. Guess things are getting cached.

If I try
```
rm -rf ~/Library/Caches/iheartla/
rm -rf iheartla/la_local_parsers/*.py
echo "5+7">test.txt
python app.py -o numpy test.txt
```

I get an error
```
Traceback (most recent call last):
  File "app.py", line 1, in <module>
    from iheartla.la_parser.parser import compile_la_file, compile_la_content, ParserTypeEnum
  File "/Users/ajx/Repos/iheartla/iheartla/la_parser/parser.py", line 31, in <module>
    from ..la_tools.parser_manager import ParserManager
  File "/Users/ajx/Repos/iheartla/iheartla/la_tools/parser_manager.py", line 4, in <module>
    from ..la_local_parsers.init_parser import grammarinitParser, grammarinitModelBuilderSemantics
ModuleNotFoundError: No module named 'iheartla.la_local_parsers.init_parser'
```

**Comment by alecjacobson** [comment]
Excellent. Excited for the script. Ideally we could have a command like:

```python app.py --regenerate-grammar```

which does all of these steps (except 2 :-))

**Comment by pressureless** [comment]
# New way to update grammar files
1. edit `.ebnf` files
2. run `python  app.py  --regenerate-grammar`

The new parser will work as long as the grammar modification doesn't include the following rules:
`KEYWORDS`, `constant`, `builtin_operators`, `func_id`, `identifier_alone`

**Comment by alecjacobson** [comment]
When I run `python app.py --regenerate-grammar`

I get an error
```
Traceback (most recent call last):
  File "app.py", line 20, in <module>
    iheartla.la_tools.parser_manager.recreate_local_parser_cache()
  File "/Users/ajx/Repos/iheartla/iheartla/la_tools/parser_manager.py", line 584, in recreate_local_parser_cache
    import iheartla.la_parser.parser
  File "/Users/ajx/Repos/iheartla/iheartla/la_parser/parser.py", line 92, in <module>
    _parser_manager = ParserManager(GRAMMAR_DIR)
  File "/Users/ajx/Repos/iheartla/iheartla/la_tools/parser_manager.py", line 24, in __init__
    self.parser_file_manager = ParserFileManager(grammar_dir)
  File "/Users/ajx/Repos/iheartla/iheartla/la_tools/parser_manager.py", line 90, in __init__
    self.load_parsers()
  File "/Users/ajx/Repos/iheartla/iheartla/la_tools/parser_manager.py", line 166, in load_parsers
    spec.loader.exec_module(module)
  File "/Users/ajx/Library/Caches/iheartla/parser_e37f0136aa3ffaf149b351f6a4c948e9_2021-05-10-13-58-11.py", line 5093
    from __future__ import generator_stop
    ^
SyntaxError: from __future__ imports must occur at the beginning of the file
```

**Comment by pressureless** [comment]
I forgot to mention the Tatsu version, the parser modification only works on `v4.4.0`

You may use `v5.5.0+`, you can check the version by
`
from tatsu._version import __version__
print("version:", __version__)
`

**Comment by pressureless** [comment]
I tried `Python v3.8.5` + `Tatsu  v5.6.1`, unfortunately, the current `.ebnf files` can not compile.

They may have changed the rules.

**Comment by yig** [comment]
If we really depend on tatsu 4.4.0 output, we should pin our tatsu version. It looks like we already do this in `pyproject.toml` and `requirements.txt`. @alecjacobson What route did you use in the end to get a python environment?

**Comment by alecjacobson** [comment]
I'm using miniconda and pip (I think). I don't really understand when I
should be calling pip install vs conda install

>

**Comment by yig** [comment]
Conda ideally manages all dependencies, but conda-forge isn't expansive enough to cover every package in the Python Package Index. So you can tell conda to use pip to install packages it doesn't natively know about. I'll make an `environment.yml`.

**Comment by yig** [comment]
Depending on your needs, choose command line (`-cli`), GUI (`-gui`), or development (`-dev`) and then:

```
conda env create -f environment-{cli,gui,dev}.yml
conda activate iheartla
```

You only need the `-dev` environment if you want to run the test suite. In conda, to run the GUI, you need to use `pythonw app.py`.

**Comment by alecjacobson** [comment]
Awesome. Thank you. This appears to have worked well. Now I can issue: 

    python app.py --regenerate-grammar
    
And I see

```
2 parsers loaded
## Clearing the cache dir: /Users/ajx/Library/Caches/iheartla
## Clearing the la_local_parsers dir: /Users/ajx/Repos/iheartla/iheartla/la_local_parsers
## Reloading the ParserManager.
0 parser loaded
## Re-creating the parsers.
## Waiting for them to be saved.
## Copying the cache dir contents into the local dir.
## Modifying default parsers
## Done.
```

I changed `⋅` to `😎` in operators `./iheartla/la_grammar/operators_ebnf.py` and then issued:

    echo "5😎7">test.txt && python app.py -o numpy test.txt
    
and indeed see

        ret = 5 * 7

in the output

😎
