### ISSUE TITLE
Double counting in sparse case statement

### ISSUE THREAD

**Issue by alecjacobson** [pressureless/linear_algebra#57]
This seems like a bug or at least ambiguous and we should clearly state what we do:

```I❤️LA
n ∈ ℤ
E ∈ {ℤ²}

A_ij = { 1 if (i,j) ∈ E
         1 if (j,i) ∈ E
         0 otherwise

where
A ∈ ℝ^(n × n)
```

Setting aside the [performance problems](https://github.com/pressureless/linear_algebra/issues/45), our codegens for numpy,cpp,matlab generate logic of the form:

```
triplets = {}
for i in 1..n
  for j in 1..n
     if (i,j) ∈ E
        triplets.push({ i, j, 1})
     if (j,i) ∈ E
        triplets.push({ i, j, 1})
A <- set_from_triplets( triplets)
```

Because all targets treat repeated entries in their respective `set_from_triplets` with `+=`, if a self-loop (i,i) appears in E, then  the correspond A(i,i) will equal `2` instead of `1` (the only acceptable interpretation of the I❤️LA code regardless of whether the second `if` case is treated as a fall-through or an `else-if`).

I'd like to propose that fall-through is not common in conventionally written math and "else if" is implied when multiply `if`s appear on the chalkboard. This also admits a simple change to our output logic:

```
triplets = {}
for i in 1..n
  for j in 1..n
     if (i,j) ∈ E
        triplets.push({ i, j, 1})
     else if (j,i) ∈ E
        triplets.push({ i, j, 1})
A <- set_from_triplets( triplets)
```

**Comment by pressureless** [comment]
If the order of `if statement` matters in I❤️LA, I think we should use `else-if`

**Comment by yig** [comment]
I agree that this should be interpreted as `else-if`. No one asked for a 2 in the presence of self-loops ((i,i) ∈ E).

It may be acceptably clear if written:
```
n ∈ ℤ
E ∈ {ℤ²}

A_ij = { 1 if (i,i) ∈ E
         1 if (i,j) ∈ E
         1 if (j,i) ∈ E
         0 otherwise

where
A ∈ ℝ^(n × n)
```

You wouldn't want a 3 for (i,i).

Consider also multiple sets:

```
n ∈ ℤ
E ∈ {ℤ²}
F ∈ {ℤ²}

A_ij = { 1 if (i,j) ∈ E
         2 if (i,j) ∈ F
         0 otherwise

where
A ∈ ℝ^(n × n)
```

You probably want E and F to be disjoint, but you also don't want a 3 in your matrix.
