### ISSUE TITLE
[question] Which characters are valid for single-character variable names?

### ISSUE THREAD

**Issue by alecjacobson** [pressureless/linear_algebra#60]
```I❤️LA
given
😎 ∈ ℝ

a = 😎
```
complains about the symbol choice
```
Error on line 2 at column 1. Failed to parse None: no available options
😎 ∈ ℝ
^
```
Is the list of valid single-symbol names located in the wiki someplace?

**Comment by alecjacobson** [comment]
[This page](https://github.com/pressureless/linear_algebra/wiki/Identifier#grammar) says ASCII but that doesn't seem to be accurate:

```I❤️LA
given
φ ∈ ℝ

a = φ
```
works fine...

**Comment by yig** [comment]
It's basically Unicode letters with optional marks. We use character categories from here: https://www.compart.com/en/unicode/category

**Comment by alecjacobson** [comment]
Thanks. so the long thing in the wiki:

    identifier_alone = !KEYWORDS (/[A-Za-z\p{Ll}\p{Lu}\p{Lo}]\p{M}*([A-Z0-9a-z\p{Ll}\p{Lu}\p{Lo}]\p{M}*)*/ | '`' /[^`]*/ '`')

contains `Ll`, `Lu` and `Lo` (as well as `A-Z0-9a-z`, are this superfluous?). Does that mean that we can use characters in

https://www.compart.com/en/unicode/category/Ll
https://www.compart.com/en/unicode/category/Lu
https://www.compart.com/en/unicode/category/Lo ?

**Comment by yig** [comment]
Yes and yes.
