### ISSUE TITLE
Fails to match matrix subtraction involving inversion

### ISSUE THREAD

**Issue by alecjacobson** [pressureless/linear_algebra#70]
This matrix expression
```
given
A ∈ ℝ^(m×m) 
B ∈ ℝ^(m×n) 
C ∈ ℝ^(n×n) 

S = C - BᵀA⁻¹B
```

incorrectly results in a parse error:

```
Error on line 6 at column 5. Dimension mismatch. Can't subtract matrix(n, n) C and matrix(n, m) Bᵀ. 
S = C - BᵀA⁻¹B
```

It seems like it's trying to parse `C-Bᵀ` which is not the correct order of operations. Perhaps `A⁻¹` getting parsed as a solve is throwing off the order of operations?

**Comment by alecjacobson** [comment]
Interesting. I thought this would at least be a work around:

```
given
A ∈ ℝ^(m×m) 
B ∈ ℝ^(m×n) 
C ∈ ℝ^(n×n) 

T = BᵀA⁻¹B
S = C - T
```

 but this gives an error:
 ```
 Error on line 7 at column 5. Dimension mismatch. Can't subtract matrix(n, n) C and matrix(n, m) T.
 ```

**Comment by pressureless** [comment]
The parsing is correct:
<img width="731" alt="image" src="https://user-images.githubusercontent.com/8511053/118414458-ac68ac00-b672-11eb-9693-7aa4416a56e8.png">


Two errors here: 
1. The dimension for `A⁻¹B` is incorrect.
2. The error msg should include `BᵀA⁻¹B` as follows
<img width="874" alt="image" src="https://user-images.githubusercontent.com/8511053/118414451-9955dc00-b672-11eb-93eb-e497f96914f6.png">
